// apps/web/app/components/Navbar.tsx
import { Link as RemixLink } from '@remix-run/react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@sscan/shared/ui/tooltip';
import { Home, LineChart, Package, Package2, Settings, ShoppingCart, Users2 } from 'lucide-react';

export function Navbar() {
	return (
		<TooltipProvider>
			<nav className="flex flex-col items-center gap-4 px-2 sm:py-5">
				<RemixLink
					to="/"
					className="group flex h-9 w-9 shrink-0 items-center justify-center gap-2 rounded-full bg-primary text-lg font-semibold text-primary-foreground md:h-8 md:w-8 md:text-base"
				>
					<Package2 className="h-4 w-4 transition-all group-hover:scale-110" />
					<span className="sr-only">Acme Inc</span>
				</RemixLink>
				<Tooltip>
					<TooltipTrigger asChild>
						<RemixLink
							to="/"
							className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
						>
							<Home className="h-5 w-5" />
							<span className="sr-only">Dashboard</span>
						</RemixLink>
					</TooltipTrigger>
					<TooltipContent side="right">Dashboard</TooltipContent>
				</Tooltip>
				<Tooltip>
					<TooltipTrigger asChild>
						<RemixLink
							to="/"
							className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent text-accent-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
						>
							<ShoppingCart className="h-5 w-5" />
							<span className="sr-only">Orders</span>
						</RemixLink>
					</TooltipTrigger>
					<TooltipContent side="right">Orders</TooltipContent>
				</Tooltip>
				<Tooltip>
					<TooltipTrigger asChild>
						<RemixLink
							to="/"
							className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
						>
							<Package className="h-5 w-5" />
							<span className="sr-only">Products</span>
						</RemixLink>
					</TooltipTrigger>
					<TooltipContent side="right">Products</TooltipContent>
				</Tooltip>
				<Tooltip>
					<TooltipTrigger asChild>
						<RemixLink
							to="/"
							className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
						>
							<Users2 className="h-5 w-5" />
							<span className="sr-only">Customers</span>
						</RemixLink>
					</TooltipTrigger>
					<TooltipContent side="right">Customers</TooltipContent>
				</Tooltip>
				<Tooltip>
					<TooltipTrigger asChild>
						<RemixLink
							to="/"
							className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
						>
							<LineChart className="h-5 w-5" />
							<span className="sr-only">Analytics</span>
						</RemixLink>
					</TooltipTrigger>
					<TooltipContent side="right">Analytics</TooltipContent>
				</Tooltip>
			</nav>
			<nav className="mt-auto flex flex-col items-center gap-4 px-2 sm:py-5">
				<Tooltip>
					<TooltipTrigger asChild>
						<RemixLink
							to="/"
							className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
						>
							<Settings className="h-5 w-5" />
							<span className="sr-only">Settings</span>
						</RemixLink>
					</TooltipTrigger>
					<TooltipContent side="right">Settings</TooltipContent>
				</Tooltip>
			</nav>
		</TooltipProvider>
	);
}

// apps/desktop/src/lib/components/Navbar.svelte
<script lang="ts">
	import { Tooltip } from '@sscan/ui';
	import { House as Home, Disc3, Package2 } from 'lucide-svelte';
</script>

<nav class="flex flex-col items-center gap-4 px-2 py-4">
	<a
		href="##"
		class="group flex h-9 w-9 shrink-0 items-center justify-center gap-2 rounded-full bg-primary text-lg font-semibold text-primary-foreground md:h-8 md:w-8 md:text-base"
	>
		<Package2 class="h-4 w-4 transition-all group-hover:scale-110" />
		<span class="sr-only">NWL NEXUS</span>
	</a>
	<Tooltip.Root>
		<Tooltip.Trigger asChild let:builder>
			<a
				href="##"
				class="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
				use:builder.action
				{...builder}
			>
				<Home class="h-5 w-5" />
				<span class="sr-only">Dashboard</span>
			</a>
		</Tooltip.Trigger>
		<Tooltip.Content side="right">Dashboard</Tooltip.Content>
	</Tooltip.Root>
	<Tooltip.Root>
		<Tooltip.Trigger asChild let:builder>
			<a
				href="##"
				class="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
				use:builder.action
				{...builder}
			>
				<Disc3 class="h-5 w-5" />
				<span class="sr-only">Orders</span>
			</a>
		</Tooltip.Trigger>
		<Tooltip.Content side="right">Orders</Tooltip.Content>
	</Tooltip.Root>
</nav>
